export const RETRO_THEME = {
  colors: {
    desktop: "var(--retro-desktop)",
    window: "var(--retro-window)",
    windowAlt: "var(--retro-window-alt)",
    surface: "var(--retro-surface)",
    inset: "var(--retro-inset)",
    insetAlt: "var(--retro-inset-alt)",
    titlebar: "var(--retro-titlebar)",
    border: "var(--retro-border)",
    borderSoft: "var(--retro-border-soft)",
    chromeText: "var(--retro-text-chrome)",
    textPrimary: "var(--retro-text-primary)",
    textMuted: "var(--retro-text-muted)",
    textSubtle: "var(--retro-text-subtle)",
    accentBlue: "var(--retro-accent-blue)",
    accentBlueText: "var(--retro-accent-blue-text)",
    accentBlueFill: "var(--retro-accent-blue-fill)",
    accentBlueFillStrong: "var(--retro-accent-blue-fill-strong)",
    accentGreen: "var(--retro-accent-green)",
    accentRed: "var(--retro-accent-red)",
    accentYellow: "var(--retro-accent-yellow)",
    tooltipBg: "var(--retro-tooltip-bg)",
  },
} as const;
